name: Action Sample

on:
  push:
    branches: 
      - master
  workflow_dispatch:

jobs:
  print-greetings:
    runs-on: ubuntu-latest
    steps:
      - name: execute echo command
        run: echo "Good Morning!"
        run: echo "Good Afternoon!"
        run: echo "Good Evening!"

